WITH CLAP_PAGADAS AS (
    SELECT
        SUBSTRING(INICIO6_TARJETA FROM 1 FOR 6) AS PRIMEROS_6_DIGITOS,
        SUBSTRING(FINAL4_TARJETA FROM -4) AS ULTIMOS_4_DIGITOS,
        ID_BANCO AS ID,
        MONTO,
        FECHA_TRANSACCION,
        ROW_NUMBER() OVER (PARTITION BY ID_BANCO ORDER BY FECHA_TRANSACCION DESC) AS RN
    FROM clap
    WHERE TIPO_TRX = 'PAGADA'
),
BANSUR_PAGADAS AS (
    SELECT
        SUBSTRING(TARJETA FROM 1 FOR 6) AS PRIMEROS_6_DIGITOS,
        SUBSTRING(TARJETA FROM 6 for 4) AS ULTIMOS_4_DIGITOS,
        ID_ADQUIRIENTE,
        MONTO,
        FECHA_TRANSACCION,
        ROW_NUMBER() OVER (PARTITION BY ID_ADQUIRIENTE ORDER BY FECHA_TRANSACCION DESC) AS RN
    FROM bansur
)
SELECT
    CP.ID,
    BP.ID_ADQUIRIENTE,
    CP.MONTO AS MONTO_CLAP,
    BP.MONTO AS MONTO_BANSUR,
    CP.FECHA_TRANSACCION AS FECHA_CLAP,
    BP.FECHA_TRANSACCION AS FECHA_BANSUR
FROM
    CLAP_PAGADAS CP
    JOIN BANSUR_PAGADAS BP ON
        CP.PRIMEROS_6_DIGITOS = BP.PRIMEROS_6_DIGITOS
        AND CP.ULTIMOS_4_DIGITOS = BP.ULTIMOS_4_DIGITOS
        AND ABS(CP.MONTO - BP.MONTO) <= 0.99
        AND CP.FECHA_TRANSACCION = BP.FECHA_TRANSACCION
        AND CP.RN = 1
        AND BP.RN = 1;